version: '3.7'
services:
  django:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
      - 5434:5432
#      - 5432:5432
#    network_mode: host
#    extra_hosts:
#      - "host.docker.internal"
#      - 5432:5432
#    env_file:
#      - ./.env.dev